### ISSUE TITLE
Listen on both HTTP and HTTPS

### ISSUE THREAD

**Issue by BrianHicks** [emilevauge/traefik#113]
It'd be pretty rad if we could listen on both HTTP and HTTPS at the same time.

**Comment by emilevauge** [comment]
@BrianHicks, yep true.
We probably need to move port into frontend section:

```toml
[backends]
  [backends.backend1]
    [backends.backend1.circuitbreaker]
      expression = "NetworkErrorRatio() > 0.5"
    [backends.backend1.servers.server1]
    url = "http://172.17.0.2:80"
    weight = 10
    [backends.backend1.servers.server2]
    url = "http://172.17.0.3:80"
    weight = 1
  [backends.backend2]
    [backends.backend2.LoadBalancer]
      method = "drr"
    [backends.backend2.servers.server1]
    url = "http://172.17.0.4:80"
    weight = 1
    [backends.backend2.servers.server2]
    url = "http://172.17.0.5:80"
    weight = 2

[frontends]
  [frontends.frontend1]
  backend = "backend2"
  port = 80
    [frontends.frontend1.routes.test_1]
    rule = "Host"
    value = "test.localhost"
  [frontends.frontend2]
  backend = "backend1"
  port = 443
  [ssl]
    certFile = "tests/traefik.crt"
    keyFile = "tests/traefik.key"
  passHostHeader = true
    [frontends.frontend2.routes.test_2]
    rule = "Path"
    value = "/test"
```
But there is also issue #61, that points the fact to be able to define multiple ports in a single frontend.
@vdemeester, @BrianHicks what do you want to do on that?
