### ISSUE TITLE
Multiple docker hosts without a cluster store

### ISSUE THREAD

**Issue by faddat** [emilevauge/traefik#182]
Hi,

It seems to me that Traefik is on the brink of killing another of docker's major "ouch!" factors:  The cluster store.  I have played with my traefik.toml some but have not been able to get it to use more than one docker host at once.  Is this expected behavior?

Thanks
-Jake

**Comment by pl1ght** [comment]
Any update on this? trying to use multiple marathon backends, will only work with one specified.

**Comment by netremo** [comment]
Anybody found solution for this issue?

**Comment by toto976** [comment]
not yet

**Comment by ViViDboarder** [comment]
It looks like this is because [`go-marathon`](https://github.com/gambol99/go-marathon) supports multiple endpoints and it's not really a Traefik feature.

**Comment by netremo** [comment]
Goal  is to be independent of any orchestration platforms. We want to manualy run microservice containers on multiple hosts and use traefik as reverse proxy.
Is it possible?

**Comment by gurumark** [comment]
+1 this would be a great feature.

**Comment by Akkarine** [comment]
> Anybody found solution for this issue?

I have an idea, but did not tried. What if you create another traefik instance and just redirect with some rule everything you need to new instance, where you'll configure another docker provider?

**Comment by eyduh** [comment]
/cast resurrect on [thread]
No but like, this would be super useful for a homelab situtation, different swarms for experiments and production etc.

Is this not being attended to because it is already a feature of traefik 2 enterprise and providing info on how to set it up would detract from profits? I read something about "multi-cluster support" on the enterprise page, so that could be it but I digress.

Would be nice to know if this is possible on traefik open source or whether I should try and emulate (with a lot more setup) a similar use case with multiple traefiks or traefik + redis/other or nginx-proxy-manager+haproxy. Would be a pity as I moved to traefik for the sweet sweet label autoconfigs but c: oh well

**Comment by olitee** [comment]
I know this isn't the solution we really want, but I've had some success within my homelab using a single instance of Traefik (running on one of two Docker hosts), and using a port-forwarding container to forward requests to the 2nd Docker host.

I'm using this container: https://hub.docker.com/r/marcnuri/port-forward to act as a port forwarder.

This container would be spun up on the same host that the Traefik container is running on - and would then redirect requests to the desired container on the OTHER Docker host.

```yml
 test-portforward:
    container_name: test-portforward
    restart: unless-stopped
    image: marcnuri/port-forward
    networks:
      - proxy
    environment: 
      - REMOTE_HOST=192.168.0.202
      - REMOTE_PORT=9002
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testservice.entrypoints=http"
      - "traefik.http.routers.testservice.rule=Host(`testservice.local.example.com`)"
      - "traefik.http.middlewares.testservice-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.testservice.middlewares=testservice-https-redirect"
      - "traefik.http.routers.testservice-secure.entrypoints=https"
      - "traefik.http.routers.testservice-secure.rule=Host(`testservice.local.example.com`)"
      - "traefik.http.routers.testservice-secure.tls=true"
      - "traefik.http.routers.testservice-secure.service=testservice"
      - "traefik.http.services.testservice.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
```
The benefit is simply consistency, and the ability to define the config using the Docker labels.

It's not much of an improvement over just simply manually adding the configuration to the traefik config. But I prefer having everything defined in my docker-compose files - and I prefer having these 'companion' containers dealing with the port forwarding and configuring the routing.

For example, on host 2 I might create a service called 'wordpress-site', and then on host 1 define a companion service named 'wordpress-site-portforward', containing the traefik lables.
