### ISSUE TITLE
traefik.domain label doesn't work (docker backend)

### ISSUE THREAD

**Issue by InAnimaTe** [EmileVauge/traefik#50]
In my `traefik.toml`:

```
 port = ":80"
 graceTimeOut = 10
 logLevel = "ERROR"

 [web]
 address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "tty0.in"
watch=true
```

My `docker-compose.yml`, setting up the proxy and a simple h5ai web index:

> Note that I want h5ai to be accessible from url `psg.mtu.edu`, *not* `psg.tty0.in`

```
proxy:
    image: emilevauge/traefik
    restart: always
    ports:
        - "80:80"
        - "8080:8080"
    volumes:
        - ./traefik.toml:/traefik.toml
        - /var/run/docker.sock:/var/run/docker.sock
http:
    image: combro2k/h5ai
    restart: always
    labels:
        - "traefik.port=80"
        - "traefik.host=psg"
        - "traefik.domain=mtu.edu"
```

Information from the WebUI:

<img width="1166" alt="screenshot 2015-10-08 13 42 10" src="https://cloud.githubusercontent.com/assets/1192726/10374679/6cd67396-6dc2-11e5-8693-28348cd5ac50.png">
