### ISSUE TITLE
Get always 404

### ISSUE THREAD

**Issue by mc388** [EmileVauge/traefik#60]
Hi,

I try to run traefik with docker. Here is my `traefik.toml` file:
```
################################################################
# Global configuration
################################################################
port = ":80"
graceTimeOut = 10logLevel = "ERROR"
################################################################
# Web configuration backend
################################################################
[web]
address = ":8080"
################################################################
# Docker configuration backend
################################################################
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
```

If I enable accessLogs I get this error:
`logger.go:24: Error opening fileopen log/access.log: no such file or directory`

Because of running docker in an ubuntu vm, I set the domain to my hosts file on my host. This works for the traefik container but not for my web application.

Here the docker-compose file from the traefik container:
```
proxy:
  image: emilevauge/traefik
  restart: always
  labels:
    - "traefik.host=proxy"
    - "traefik.domain=dev.io"
  ports:
    - "80:80"
    - "443:443"
    - "8080:8080"
  volumes:
    - ./conf/traefik.toml:/traefik.toml
    - /var/run/docker.sock:/var/run/docker.sock
```

And here from my web application:
```
web:
  image: nginx:latest
  ports:
    - "40020:80"
    - "40021:443"
  labels:
    - "traefik.host=astitvam"
    - "traefik.domain=dev.io"
  links:
    - "php"
  volumes:
    - ./logs/nginx:/var/log/nginx
    - ./nginx/ssl:/etc/nginx/ssl
  volumes_from:
    - php

php:
  image: mc388/docker-php:latest
  volumes:
    - ./:/var/www/html
```

The web application shows always `404 page not found`.

And two last questions:
1. How can I say traefik to use port 80 and 443 or set force ssl?
2. How can I set up different ssl certs for different web applications?
