### ISSUE TITLE
No way to serve at root/default domain

### ISSUE THREAD

**Issue by InAnimaTe** [emilevauge/traefik#64]
If my default domain is `tty0.in`, other than just serving on subdomains via the `traefik.host` declaration or the default `{container_name}.{domain}` moniker, it should be possible to serve for requests that come in directly to `tty0.in` i.e. a splash page or whatever.

I've tried a couple ways of doing this:

In my `traefik.toml` under the Docker section:

```
# Default domain used.
# Can be overridden by setting the "traefik.domain" label on a container.
#
# Required
#
domain = "tty0.in"
```

My `docker-compose.yml` defining a 0bin paste service I'd like served at the root:

```
paste:
    image: inanimate/0bin:0.5
    restart: always
    labels:
        - "traefik.port=8000"
        - "traefik.host="
```
I've also tried explicitly setting the domain via `"traefik.domain=tty0.in"` to no avail (same thing happens):

![screenshot 2015-10-14 14 54 53](https://cloud.githubusercontent.com/assets/1192726/10494519/c2572146-7284-11e5-8c49-5e7d85bfa454.png)

A period gets prepended and visiting returns a `404 page not found`
