### ISSUE TITLE
boltdb backend fails to start

### ISSUE THREAD

**Issue by BrianHicks** [emilevauge/traefik#68]
When using the configuration:

```toml
port = ":80"
graceTimeOut = 10
logLevel = "ERROR"

[boltdb]
endpoint = "/etc/traefik/traefik.db"
watch = true
prefix = "/traefik"
```

Traefik starts with the message:

`time="2015-10-15T19:31:08Z" level=error msg="Error starting provider boltBucket config option missing"`

The same thing happens when I substitute `boltBucket` for `prefix` in the config.
