### ISSUE TITLE
Add a Traefik frontend route

### ISSUE THREAD

**Issue by solher** [emilevauge/traefik#75]
I think that would be cool to allow the Traefik frontend to have a domain and be consistent with the rest of the routing system.
I would personally like to be able to have traefik.domain.com for the dashboard and not forced to use a raw domain.com:8080.

Or maybe there is a workaround I don't find.

**Comment by emilevauge** [comment]
This works, using file configuration backend:

```toml
[backends.ui]
    [backends.ui.servers.traefik]
    url = "http://localhost:8080"
    weight = 1

[frontends]
  [frontends.ui]
  backend = "ui"
    [frontends.ui.routes.traefik]
    rule = "Host"
    value = "traefik.domain.com"
```
